### ISSUE TITLE
Play media in a loop

### ISSUE THREAD

**Issue by 5rzmz8odb** [allejok96/ffcam#2]
Nice job!
A good iteration will be to allow a loop video playing for example

**Comment by allejok96** [comment]
Thanks, but since the tweaking possibilities are endless with ffmpeg, I won't include any such feature requests. See this project as a template for further customization, or as a showcase.

If you want looping video, adding `-stream_loop -1` to [line 134](https://github.com/allejok96/ffcam/blob/master/ffcam.sh#L134) should do it. Then of course you could do some crazieness like:

    ffmpeg [options] $(zenity --question --text "Loop?" && echo -stream_loop -1) [options]
